set(CMAKE_MODULE_PATH "C:/Users/elyde/git_repo_CMake/Modules")
set(CMAKE_FIND_ROOT_PATH, "c:/mysys2/mingw/x86_64-w64-mingw32")
set(EXTRACTED_SOURCES_PATH "g:/mingw_libs")

set(SDLDIR "${EXTRACTED_SOURCES_PATH}/SDL2-2.0.7/x86_64-w64-mingw32")
set(SDL_LIBRARY"${EXTRACTED_SOURCES_PATH}/SDL2-2.0.7/x86_64-w64-mingw32/lib/SDL.dll")
set(SDL_INCLUDE_DIR "${EXTRACTED_SOURCES_PATH}/include/SDL2")

set(SDLIMGDIR "${EXTRACTED_SOURCES_PATH}/SDL2_image-2.0.2/x86_64-w64-mingw32")
set(SDL_IMAGE_LIBRARY "${EXTRACTED_SOURCES_PATH}/lib")
set(SDL_IMAGE_INCLUDE_DIR "${EXTRACTED_SOURCES_PATH}/include/SDL2")
